# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\1209\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pose
import face_reco_from_camera_ot as frfco

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(692, 809)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MainBox = QtWidgets.QVBoxLayout()
        self.MainBox.setContentsMargins(-1, -1, -1, 0)
        self.MainBox.setObjectName("MainBox")
        self.TopBox = QtWidgets.QHBoxLayout()
        self.TopBox.setObjectName("TopBox")
        self.Camopen = QtWidgets.QPushButton(self.centralwidget)
        self.Camopen.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.Camopen.setFont(font)
        self.Camopen.setObjectName("Camopen")
        self.TopBox.addWidget(self.Camopen)
        self.Camstop = QtWidgets.QPushButton(self.centralwidget)
        self.Camstop.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.Camstop.setFont(font)
        self.Camstop.setObjectName("Camstop")
        self.TopBox.addWidget(self.Camstop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TopBox.addItem(spacerItem)
        self.MainBox.addLayout(self.TopBox)
        self.MidBox = QtWidgets.QHBoxLayout()
        self.MidBox.setObjectName("MidBox")
        self.view = QtWidgets.QScrollArea(self.centralwidget)
        self.view.setMinimumSize(QtCore.QSize(670, 670))
        self.view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.view.setWidgetResizable(True)
        self.view.setObjectName("view")
        self.viewform = QtWidgets.QWidget()
        self.viewform.setGeometry(QtCore.QRect(0, 0, 651, 651))
        self.viewform.setObjectName("viewform")
        self.viewdata = QtWidgets.QLabel(self.viewform)
        self.viewdata.setGeometry(QtCore.QRect(0, 0, 650, 650))
        self.viewdata.setMinimumSize(QtCore.QSize(650, 650))
        self.viewdata.setObjectName("viewdata")
        self.view.setWidget(self.viewform)
        self.MidBox.addWidget(self.view)
        self.MainBox.addLayout(self.MidBox)
        self.botBox = QtWidgets.QHBoxLayout()
        self.botBox.setObjectName("botBox")
        self.viewCBO_roi = QtWidgets.QComboBox(self.centralwidget)
        self.viewCBO_roi.setMinimumSize(QtCore.QSize(80, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.viewCBO_roi.setFont(font)
        self.viewCBO_roi.setObjectName("viewCBO_roi")
        self.viewCBO_roi.addItem("")
        self.viewCBO_roi.addItem("")
        self.viewCBO_roi.addItem("")
        self.viewCBO_roi.addItem("")
        self.viewCBO_roi.addItem("")
        self.botBox.addWidget(self.viewCBO_roi)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.botBox.addItem(spacerItem1)
        self.MainBox.addLayout(self.botBox)
        self.verticalLayout_2.addLayout(self.MainBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Camopen.clicked.connect(self.onButton1Click)
        self.Camstop.clicked.connect(self.onButton2Click)
        
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Webcam_example"))
        self.Camopen.setText(_translate("MainWindow", "Open"))
        self.Camstop.setText(_translate("MainWindow", "Close"))
        self.viewdata.setText(_translate("MainWindow", "TextLabel"))
        self.viewCBO_roi.setItemText(0, _translate("MainWindow", "0.50"))
        self.viewCBO_roi.setItemText(1, _translate("MainWindow", "0.75"))
        self.viewCBO_roi.setItemText(2, _translate("MainWindow", "1.00"))
        self.viewCBO_roi.setItemText(3, _translate("MainWindow", "1.25"))
        self.viewCBO_roi.setItemText(4, _translate("MainWindow", "1.50"))
    def onButton1Click(self):
        self.Camopen.setText('hello wolrd')
        #subprocess.call("pose detection.py", shell=True)
        #exec(open("pose detection.py", encoding="utf-8").read())
        pose.pose_detect()
    def onButton2Click(self):
        self.Camstop.setText('hello wolrd')
        #subprocess.call("pose detection.py", shell=True)
        #exec(open("pose detection.py", encoding="utf-8").read())
        #pose.pose_detect()
        frfco.main()
        
if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
